In [9]:
import pandas as pd
import os
import requests
import tables
import streamlit as st
import re

In [5]:
gtex = pd.read_hdf("/Users/s2096435/Library/CloudStorage/OneDrive-UniversityofEdinburgh/test_code_review/tarviz//data/bulk-qtl_v8_multi-tissue-qtl_GTEx_Analysis_v8.hdf5")

In [6]:
gtex

,RSID,#STUDY,PVALUE_FE,BETA_FE,STD_FE,PVALUE_RE,BETA_RE,STD_RE,PVALUE_RE2,STAT1_RE2,...,mval_Small_Intestine_Terminal_Ileum,mval_Spleen,mval_Stomach,mval_Testis,mval_Thyroid,mval_Uterus,mval_Vagina,mval_Whole_Blood,VARIANT_CODE,ENSEMBL
0,"chr1_14677_G_A_b38,ENSG00000228327.3",49,1.123430e-254,0.638840,0.018741,7.731270e-105,0.669309,0.030780,4.786920e-260,1161.97000,...,1.000,1.000,1.000,0.000,1.000,1.000,1.000,0.000,chr1_14677_G_A_b38,ENSG00000228327.3
1,"chr1_14677_G_A_b38,ENSG00000228463.9",49,1.212340e-149,-0.648482,0.024890,7.372880e-66,-0.682953,0.039844,3.126990e-157,678.81000,...,0.993,0.305,1.000,0.521,1.000,0.944,0.939,0.000,chr1_14677_G_A_b38,ENSG00000228463.9
2,"chr1_14677_G_A_b38,ENSG00000241860.6",44,8.827740e-191,0.818824,0.027793,4.609200e-111,0.838671,0.037452,5.144700e-193,868.01200,...,1.000,1.000,1.000,0.993,1.000,1.000,1.000,0.000,chr1_14677_G_A_b38,ENSG00000241860.6
3,"chr1_16841_G_T_b38,ENSG00000279457.4",49,5.249250e-29,-0.288613,0.025821,5.249250e-29,-0.288613,0.025821,2.468910e-28,124.93900,...,1.000,0.936,0.877,0.996,1.000,0.988,0.981,0.996,chr1_16841_G_T_b38,ENSG00000279457.4
4,"chr1_17005_A_G_b38,ENSG00000227232.5",49,6.832020e-49,-0.541506,0.036847,7.435180e-48,-0.541863,0.037284,4.091780e-48,215.97400,...,0.972,1.000,1.000,0.942,1.000,0.998,0.972,0.999,chr1_17005_A_G_b38,ENSG00000227232.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13791904,"chrX_156007058_A_G_b38,ENSG00000185203.12",4,5.831510e-21,-0.517496,0.055094,5.831510e-21,-0.517496,0.055094,1.301460e-20,88.22840,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chrX_156007058_A_G_b38,ENSG00000185203.12
13791905,"chrX_156008220_A_G_b38,ENSG00000168939.11",49,5.739090e-02,0.075064,0.039501,5.739090e-02,0.075064,0.039501,8.254320e-02,3.61122,...,0.613,0.450,0.663,0.444,0.628,0.507,0.498,0.556,chrX_156008220_A_G_b38,ENSG00000168939.11
13791906,"chrX_156023203_T_A_b38,ENSG00000168939.11",49,6.758740e-03,0.028230,0.010423,1.356000e-02,0.028412,0.011509,8.138280e-03,7.33599,...,0.330,0.428,0.245,0.173,0.981,0.390,0.269,0.431,chrX_156023203_T_A_b38,ENSG00000168939.11
13791907,"chrX_156025583_C_T_b38,ENSG00000185973.10",49,1.085950e-01,0.014351,0.008944,1.085950e-01,0.014351,0.008944,1.127550e-01,2.57455,...,0.339,0.237,0.195,0.110,0.100,0.106,0.153,0.021,chrX_156025583_C_T_b38,ENSG00000185973.10
13791908,"chrX_156025583_C_T_b38,ENSG00000224216.1",26,4.825150e-02,-0.047375,0.023986,5.897850e-02,-0.053885,0.028535,7.857230e-02,3.90120,...,0.277,0.467,NaN,NaN,0.207,0.295,0.230,0.196,chrX_156025583_C_T_b38,ENSG00000224216.1

In [7]:
def extract_chr(rsid):
    match = re.match(r'chr([0-9XY]+)_', rsid)
    if match:
        return match.group(1)
    return None

In [10]:
gtex['Chromosome'] = gtex['RSID'].apply(extract_chr)

In [15]:
chromosome_dfs = {chr_num: df_sub for chr_num, df_sub in gtex.groupby('Chromosome')}

In [18]:
for chr_num, df_sub in chromosome_dfs.items():
    filename = f'/Users/s2096435/Library/CloudStorage/OneDrive-UniversityofEdinburgh/test_code_review/tarviz/chrom/chr{chr_num}.hdf5'
    df_sub.to_hdf(filename, key='RSID', mode='w')

In [20]:
pd.read_hdf("/Users/s2096435/Library/CloudStorage/OneDrive-UniversityofEdinburgh/test_code_review/tarviz/chrom/chr1.hdf5")

,RSID,#STUDY,PVALUE_FE,BETA_FE,STD_FE,PVALUE_RE,BETA_RE,STD_RE,PVALUE_RE2,STAT1_RE2,...,mval_Spleen,mval_Stomach,mval_Testis,mval_Thyroid,mval_Uterus,mval_Vagina,mval_Whole_Blood,VARIANT_CODE,ENSEMBL,Chromosome
0,"chr1_14677_G_A_b38,ENSG00000228327.3",49,1.123430e-254,0.638840,0.018741,7.731270e-105,0.669309,0.030780,4.786920e-260,1161.9700,...,1.000,1.000,0.000,1.000,1.000,1.000,0.000,chr1_14677_G_A_b38,ENSG00000228327.3,1
1,"chr1_14677_G_A_b38,ENSG00000228463.9",49,1.212340e-149,-0.648482,0.024890,7.372880e-66,-0.682953,0.039844,3.126990e-157,678.8100,...,0.305,1.000,0.521,1.000,0.944,0.939,0.000,chr1_14677_G_A_b38,ENSG00000228463.9,1
2,"chr1_14677_G_A_b38,ENSG00000241860.6",44,8.827740e-191,0.818824,0.027793,4.609200e-111,0.838671,0.037452,5.144700e-193,868.0120,...,1.000,1.000,0.993,1.000,1.000,1.000,0.000,chr1_14677_G_A_b38,ENSG00000241860.6,1
3,"chr1_16841_G_T_b38,ENSG00000279457.4",49,5.249250e-29,-0.288613,0.025821,5.249250e-29,-0.288613,0.025821,2.468910e-28,124.9390,...,0.936,0.877,0.996,1.000,0.988,0.981,0.996,chr1_16841_G_T_b38,ENSG00000279457.4,1
4,"chr1_17005_A_G_b38,ENSG00000227232.5",49,6.832020e-49,-0.541506,0.036847,7.435180e-48,-0.541863,0.037284,4.091780e-48,215.9740,...,1.000,1.000,0.942,1.000,0.998,0.972,0.999,chr1_17005_A_G_b38,ENSG00000227232.5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1119416,"chr1_248929755_A_C_b38,ENSG00000233084.2",46,1.047980e-07,0.220954,0.041547,5.714550e-07,0.217683,0.043531,8.743050e-08,28.2833,...,0.772,0.893,1.000,0.744,0.620,0.713,0.243,chr1_248929755_A_C_b38,ENSG00000233084.2,1
1119417,"chr1_248930892_C_G_b38,ENSG00000177212.3",8,7.501820e-04,-0.343006,0.101766,7.922680e-02,-0.290373,0.165437,1.726750e-04,11.3606,...,NaN,NaN,0.538,0.984,NaN,NaN,NaN,chr1_248930892_C_G_b38,ENSG00000177212.3,1
1119418,"chr1_248930892_C_G_b38,ENSG00000233084.2",46,1.163580e-09,0.281528,0.046265,3.362490e-08,0.276526,0.050082,8.617170e-10,37.0295,...,0.822,0.873,1.000,0.406,0.515,0.774,0.267,chr1_248930892_C_G_b38,ENSG00000233084.2,1
1119419,"chr1_248936836_GC_G_b38,ENSG00000233084.2",46,1.463150e-37,-0.148614,0.011602,1.336660e-26,-0.153380,0.014369,2.874150e-37,164.0660,...,1.000,0.962,1.000,1.000,0.970,0.956,0.889,chr1_248936836_GC_G_b38,ENSG00000233084.2,1
1119420,"chr1_248937425_A_G_b38,ENSG00000233084.2",46,5.096010e-11,0.149444,0.022753,5.096010e-11,0.149444,0.022753,1.162170e-10,43.1400,...,0.801,0.897,0.776,0.988,0.623,0.771,0.700,chr1_248937425_A_G_b38,ENSG00000233084.2,1